;; Disable signature checking for packages
(setq package-check-signature nil)

;; Load the package management system
(require 'package)

;; Add package archives
(setq package-archives
      '(("gnu" . "https://elpa.gnu.org/packages/")
        ("melpa" . "https://stable.melpa.org/packages/")))

;; Initialize the package system
(package-initialize)

;; Install use-package if it is not already installed
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

;; Ensure use-package is available
(require 'use-package)
(setq use-package-always-ensure t)

;; Custom-set-variables (generated by Custom)
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-enabled-themes '(monokai-pro))
 '(ispell-dictionary nil)
 '(package-selected-packages '(typescript-mode use-package web-mode)))

;; Enable line numbers globally
(global-display-line-numbers-mode 1)


;; Custom-set-faces (generated by Custom)
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "#1B1E1B" :foreground "#F5F5F5" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 1 :width normal :foundry "default" :family "default")))))

;; Set indentation preferences
(setq-default indent-tabs-mode nil)
(setq-default tab-width 4)
(setq indent-line-function 'insert-tab)
(setq sgml-basic-offset 1)
(setq js-indent-level 2)
(setq typescript-indent-level 2)

;; Other custom settings
(add-hook 'emacs-startup-hook 'toggle-window-split)
(when (fboundp 'electric-indent-mode) (electric-indent-mode -1))
(setq split-height-threshold nil)
(setq split-width-threshold 0)

;; Keybindings
(global-set-key "\C-h" 'delete-backward-char)
(global-set-key "\C-xh" 'help-command)

;; Use web-mode for HTML, JSX, and TSX files
(use-package web-mode
  :mode ("\\.html?\\'" "\\.tsx\\'" "\\.jsx\\'"))

;; Add additional auto-mode-alist entries
(add-to-list 'auto-mode-alist '("\\.tsx\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.jsx\\'" . web-mode))
